#!/bin/sh
#
# Default Memory Map for DM3730 EVM
#
# Start Addr    Size    Description
# -------------------------------------------
# 0x80000000     55 MB  Linux
# 0x83700000     34 MB  CMEM
# 0x85900000     39 MB  CODEC SERVER

load () {
    modprobe cmemk phys_start=0x83700000 phys_end=0x85900000 allowOverlap=1 useHeapIfPoolUnavailable=1
    modprobe dsplinkk
    modprobe lpm_omap3530
    modprobe sdmak
    amixer cset name='HeadsetL Mixer AudioL1' on
    amixer cset name='HeadsetR Mixer AudioR1' on
    amixer -c 0 set Headset 1+ unmute 
}

unload () {
    rmmod cmemk 2>/dev/null
    rmmod lpm_omap3530 2>/dev/null
    rmmod dsplinkk 2>/dev/null
    rmmod sdmak 2>/dev/null
}

case "$1" in
      start) 
            load
             ;;
       stop) 
            unload           
             ;;
       restart) 
            unload           
            load
             ;;
        *)
             echo "$0 <start/stop/restart>"
             ;;
esac

